apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  #replicas set resource labels
  labels:
    purpose: taint-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      purpose: taint-demo
      project: roboshop
      #pod definition
  template:
    metadata:
      labels:
        project: roboshop
        purpose: taint-demo
    spec:
      containers:
        - name: nginx
          image: nginx

# kubectl taint nodes ip-192-168-52-96.ec2.internal project=roboshop:NoSchedule
# node/ip-192-168-52-96.ec2.internal tainted

#k9s
# curl -sS https://webinstall.dev/k9s | bash